In [ ]:
import pandas as pd 
import pandas_profiling
import numpy as np

In [ ]:
import pyforest
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

pd.set_option('display.max_columns', 300)

In [ ]:
data= pd.read_csv("data/training_data(new).csv")

In [12]:
data

,profile_ID,DOB,Contact_type,Gender,Pack_ID,Start_Date,Status,Upgradable,Validity_End,Country,...,Subscription Type,Billing Type,Customer Longevity,Advertise / Video,networkStrength,appVersion,platform,cdn,Contract Term,Contract Amount
0,rsanchez,6/10/2005,Email,Female,432281,10/28/2021,INACTIVE,YES,12/5/2022,India,...,12,Paytm,4,Video,,macOS Ventura 13.0.1,YouTube TV,Cloudfront,12 Months,1500.0
1,rsanchez,6/10/2005,Email,Female,432281,10/28/2021,INACTIVE,YES,12/5/2022,India,...,12,Paytm,4,Video,,Windows 10,Disney + Hotstar,Cloudfront,3 Months,650.0
2,rsanchez,6/10/2005,Email,Female,432281,10/28/2021,INACTIVE,YES,12/5/2022,India,...,12,Paytm,4,Video,,macOS Ventura 13.0.1,Sonyliv,Akamai,1 Month,350.0
3,rsanchez,6/10/2005,Email,Female,432281,10/28/2021,INACTIVE,YES,12/5/2022,India,...,12,Paytm,4,Advertise,,Xcode 14.1,Sling TV,Cloudfront,1 Month,350.0
4,rsanchez,6/10/2005,Email,Female,432281,10/28/2021,INACTIVE,YES,12/5/2022,India,...,12,Paytm,4,Video,,Android TV 12.3.2,Sonyliv,Cloudfront,3 Months,650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332119,kathleen63,5/28/1989,WhatsApp,Genderqueer,433001,7/24/2021,ACTIVE,NO,12/11/2022,India,...,12,Paytm,4,Advertise,,macOS Ventura 13.0.1,Facebook Watch,Cloudfront,NaN,NaN
332120,kathleen63,5/28/1989,WhatsApp,Genderqueer,433001,7/24/2021,ACTIVE,NO,12/11/2022,India,...,12,Paytm,4,Video,,Xcode 14.1,HBO Max,Akamai,NaN,NaN
332121,kathleen63,5/28/1989,WhatsApp,Genderqueer,433001,7/24/2021,ACTIVE,NO,12/11/2022,India,...,12,Paytm,4,Video,,None,Jio Tv,Cloudfront,NaN,NaN
332122,kathleen63,5/28/1989,WhatsApp,Genderqueer,433001,7/24/2021,ACTIVE,NO,12/11/2022,India,...,12,Paytm,4,Advertise,,FireOS 7.6.1.3,Disney + Hotstar,Cloudfront,NaN,NaN
332123,kathleen63,5/28/1989,WhatsApp,Genderqueer,433001,7/24/2021,ACTIVE,NO,12/11/2022,India,...,12,Paytm,4,Video,,Extension 6.5,Sling TV,Akamai,NaN,NaN

In [13]:
data.describe()

,Pack_ID,avg_dur,num_devs,Subscription Type,Customer Longevity,Contract Amount
count,332124.000000,332124.000000,332124.000000,332124.000000,332124.000000,1104.000000
mean,432659.408089,1324.298012,18.602507,6.856578,2.830389,891.394928
std,287.044077,370.010235,4.538854,4.494624,1.108986,417.785957
min,432156.000000,475.933333,4.000000,1.000000,1.000000,350.000000
25%,432416.000000,1047.235294,16.000000,3.000000,2.000000,650.000000
50%,432662.000000,1286.000000,18.000000,6.000000,3.000000,950.000000
75%,432908.000000,1554.500000,21.000000,12.000000,4.000000,1500.000000
max,433155.000000,2926.000000,42.000000,12.000000,4.000000,1500.000000